#!/usr/bin/env python3
"""Everybody in SkyBlock, and what they talk about.

Read by tools/make_content.py, which turns each entry into an item you can
place and a conversation they have when you right-click them.

    (id, name, where they are, [what they say], the quest they give)

What is real and what is not
----------------------------
The names, the islands and the jobs are the game's, taken from the wiki's NPC
tables -- who exists, where they stand, and what each of them is for. That is
the part that matters and the part this mod would otherwise be guessing at.

The lines themselves are written here from those descriptions rather than
ripped out of Hypixel's server. So Vex talks about trading because Vex talks
about trading, and Tom hands you the Promising Axe recipe because that is what
Tom does -- but the exact sentences are this mod's own. An empty quest string
means they have no quest, which is most of them.
"""

NPCS = [
    # ---------------------------------------------------------- your island
    ("jerry", "Jerry", "Private Island",
     ["Hey there! Welcome to your very own island.",
      "There's a tree, and there's a portal. Everything else is up to you.",
      "Bridge across. I'll wait."], "Getting Started"),
    ("sam", "Sam", "Private Island",
     ["You made it to SkyBlock Level 5. Not bad at all.",
      "I turn up when you've proved you're sticking around."], ""),
    ("alice", "Alice", "Private Island — Reforge Anvil",
     ["Bring me a weapon and some coins and I'll reforge it.",
      "Different stone, different stats. Your choice."], ""),
    ("iris", "Iris", "Private Island — Reforge Anvil",
     ["The anvil's mine today. Alice can wait her turn.",
      "Reforging never breaks anything. Worst case it's a worse roll."], ""),
    ("nina", "Nina", "Private Island — Reforge Anvil",
     ["Reforges, on your own island. No walk to the Blacksmith.",
      "Cheaper than you'd think, too."], ""),
    ("jeanne", "Jeanne", "Private Island — Reforge Anvil",
     ["Put it on the anvil and stand back."], ""),
    ("lou", "Lou", "Private Island — Reforge Anvil",
     ["Reforge stones go here. Ordinary reforges go there."], ""),
    ("sarah", "Sarah", "Private Island — Reforge Anvil",
     ["Anything with stats can be reforged. Anything."], ""),
    ("oceane", "Oceane", "Private Island — Reforge Anvil",
     ["I've reforged a thousand swords and never seen the same roll twice."], ""),
    ("cramille", "Cramille", "Private Island — Reforge Anvil",
     ["You're paying for the chance, not the result. Remember that."], ""),
    ("chloe", "Chloe", "Private Island — Reforge Anvil",
     ["Armour first. Armour keeps you alive long enough to use the sword."], ""),
    ("pauline", "Pauline", "Private Island — Reforge Anvil",
     ["Anvil's free. Go on."], ""),
    ("manon", "Manon", "Private Island — Reforge Anvil",
     ["I do this all day and I still like the sound it makes."], ""),
    ("maxime", "Maxime", "Private Island — Reforge Anvil",
     ["One reforge, one price, no haggling."], ""),
    ("margaux", "Margaux", "Private Island — Reforge Anvil",
     ["Rare things reforge dearer. That's just how it is."], ""),
    ("mathilde", "Mathilde", "Private Island — Reforge Anvil",
     ["Come back when you've something worth improving."], ""),
    ("lea", "Lea", "Private Island — Reforge Anvil",
     ["Last one on the rota. Lucky you."], ""),

    # --------------------------------------------------------- the village
    ("andrew", "Andrew", "Village",
     ["There's a whole forum full of people arguing about this game.",
      "Worth a read. Mostly."], "Introducing Yourself"),
    ("duke", "Duke", "Village",
     ["The Farm's out east and the Coal Mine's under the hill.",
      "Wheat first, coal after. That's the order most people find works."], ""),
    ("leo", "Leo", "Village",
     ["West of here it's all trees. The Forest, we call it.",
      "Foraging levels come out of that wood faster than anywhere else."], ""),
    ("liam", "Liam", "Village",
     ["They keep saying we'll be able to rent these houses one day.",
      "I'll believe it when somebody hands me a key."], ""),
    ("lynn", "Lynn", "Village",
     ["Everything you've been asked to do is written down in the Quest Log.",
      "Type /quests. Saves asking me."], ""),
    ("jack", "Jack", "Village",
     ["Your stats are Health, Defence, Strength, Speed and Crit.",
      "All of them come off what you're wearing and what you're carrying."], ""),
    ("jamie", "Jamie", "Village",
     ["Mana's the blue bar. Abilities eat it and it fills itself back up.",
      "Here — take this Rogue Sword. Now you've something to spend it on."], ""),
    ("tom", "Tom", "Village",
     ["The Recipe Book knows more recipes than you do.",
      "Take the Promising Axe recipe while you're here."], ""),
    ("ryu", "Ryu", "Village",
     ["Nine Skills: Farming, Mining, Combat, Foraging, Fishing and the rest.",
      "Every one of them levels by doing it. None of them by asking me."], ""),
    ("stella", "Stella", "Village",
     ["A Profile is a whole separate game. You can have several.",
      "Play one with a friend and that's a Co-op."], ""),
    ("vex", "Vex", "Village",
     ["Trading. Two people, two chests, nobody gets robbed.",
      "Here, have a dead bush for your trouble."], ""),
    ("felix", "Felix", "Village",
     ["An Ender Chest follows you everywhere you go.",
      "Put the things you'd cry about losing in there."], ""),
    ("security_sloth", "Security Sloth", "Village",
     ["Somebody in chat offering you a mod that gives free coins?",
      "It doesn't give free coins. It gives them your account."], ""),
    ("maths_enjoyer", "Maths Enjoyer", "Village",
     ["Magical Power. It's the square root, times the count, over ten.",
      "Nobody ever wants to hear the rest of it."], ""),
    ("baker", "Baker", "Village",
     ["New Year Cake, once a SkyBlock year, and never the same one twice.",
      "Collect them. Don't eat them."], ""),
    ("bingo", "Bingo", "Village",
     ["New month, new Bingo card. Fresh profile, no head start.",
      "I'm only here at the start of one."], ""),
    ("alixer", "Alixer", "Village",
     ["Bingo profiles only. Show me your rank and I'll show you a potion."], ""),
    ("hub_selector", "Hub Selector", "Village",
     ["Too crowded? I'll drop you in another Hub.",
      "Same island, different people."], ""),
    ("adventurer", "Adventurer", "Village",
     ["Rotten flesh, bones, string, gunpowder. I buy all of it.",
      "And I sell it back to whoever forgot to go and get some."], ""),
    ("alchemist", "Alchemist", "Village",
     ["Brewing stands, glass bottles, and the Nether Wart to fill them.",
      "Everything worth drinking starts with wart."], ""),
    ("tyashoi_alchemist", "Tyashoi Alchemist", "Village",
     ["Odd brews. Odder prices."], ""),
    ("builder", "Builder", "Village",
     ["Every decorative block there is, and I do mean every one.",
      "Bring coins. Bring a lot of coins."], ""),
    ("wool_weaver", "Wool Weaver", "Village",
     ["Wool in sixteen colours, hardened clay, and glass to match.",
      "String makes wool. Wool makes everything else."], ""),
    ("amelia", "Amelia", "Village",
     ["Social things. Party hats, banners, the sort of thing you wave about."], ""),
    ("librarian", "Librarian", "Village",
     ["Experience bottles, books, and enchanted books.",
      "Quiet, please. Some of us are reading."], ""),
    ("guy", "Guy", "Village",
     ["Your Personal Bank only holds so much. I'll widen it.",
      "For a fee, obviously."], ""),
    ("dusk", "Dusk", "Village",
     ["Runecrafting. You put runes on things and the things glow.",
      "It is more complicated than that, but not much."], ""),
    ("carpenter", "Carpenter", "Village",
     ["Carpentry. Furniture, mostly, and some of it does something."], ""),
    ("oringo", "Oringo the Traveling Zookeeper", "Village",
     ["Pets. Every one of them favours a Skill.",
      "Feed it, level it, and it pays you back."], ""),
    ("fear_mongerer", "Fear Mongerer", "Village",
     ["Candy only. I don't take coins and I don't explain why."], ""),
    ("salesman", "Salesman", "Village",
     ["Furniture and Minion Skins, for those who've paid for the privilege."], ""),
    ("plumber_joe", "Plumber Joe", "Village",
     ["Plumber's Sponge. Soaks up what you'd rather not stand in."], ""),
    ("seraphine", "Seraphine", "Community Center",
     ["The Community Center is where everyone's coins go to build things.",
      "Everything in here got paid for by somebody."], ""),
    ("elizabeth", "Elizabeth", "Community Center",
     ["The Community Shop. Bits only, and Bits come from Fame.",
      "No, you can't buy Bits."], ""),
    ("biblio", "Biblio", "Community Center",
     ["There is a wiki. It knows more than any of us.",
      "It certainly knows more than Duke."], ""),
    ("banker", "Banker", "The Bank",
     ["Coins in your pocket are coins you can lose.",
      "Dying costs you half of what you carry, and none of what I hold.",
      "Put some with me and sleep easier."], "Saving Up"),
    ("auction_master", "Auction Master", "Auction House",
     ["Put a thing up, name a price, walk away.",
      "Or don't wait — I'll take the lot off you right now."], ""),
    ("auction_agent", "Auction Agent", "Auction House",
     ["Four of us and one Auction Master. You do the maths.",
      "Anything he handles, I handle."], ""),
    ("bazaar", "Bazaar", "Bazaar Alley",
     ["Buy orders, sell orders, and a spread in between.",
      "That spread is how I eat."], ""),
    ("bazaar_agent", "Bazaar Agent", "Bazaar Alley",
     ["Same stock as the Bazaar, shorter queue."], ""),
    ("blacksmith", "Blacksmith", "Village",
     ["Reforging's my trade. Bring something with stats on it.",
      "And mine ten coal while you're about it, then get to the Gold Mine."],
     "Time to Mine"),
    ("weaponsmith", "Weaponsmith", "Village",
     ["Swords and bows for people who intend to use them.",
      "Rosetta's next door for armour."], ""),
    ("rosetta", "Rosetta", "Village",
     ["Armour. Wear the whole set — half a set is half nothing."], ""),
    ("mine_merchant", "Mine Merchant", "Village",
     ["Ores, stone, and a pickaxe to get at them."], ""),
    ("lumber_merchant", "Lumber Merchant", "Village",
     ["Wood and axes. Twenty logs and you'll have Foraging I."],
     "Foraging Tutorial"),
    ("farm_merchant", "Farm Merchant", "Village",
     ["Crops and seeds, bought and sold, all day long."], ""),
    ("fishing_merchant", "Fishing Merchant", "Fish Shop",
     ["Whatever the water gives you, I'll buy.",
      "Clownfish and pufferfish fetch the most."], ""),
    ("anita", "Anita", "Village",
     ["Farm equipment, and upgrades if you've won Jacob's Tickets."], ""),
    ("jacob", "Jacob", "Village",
     ["Farming Contests. Three crops, twenty minutes, everyone at once.",
      "Win one and I'll pay you in Tickets."], ""),
    ("jacobus", "Jacobus", "Thaumaturgist",
     ["Your Accessory Bag is too small. I can fix that for coins."], ""),
    ("ozanne", "Ozanne", "Thaumaturgist",
     ["Reforged an accessory and regretted it? I'll refund the stone."], ""),
    ("maxwell", "Maxwell", "Thaumaturgist",
     ["Power Stones. One at a time, and it changes everything in the bag."], ""),
    ("bea", "Bea", "Pet Shop",
     ["Bee pets. They're very good and they know it."], ""),
    ("kat", "Kat", "Pet Shop",
     ["Leave a pet with me and it comes back rarer.",
      "It takes as long as it takes."], ""),
    ("george", "George", "Pet Shop",
     ["I buy pets. I don't ask where they came from."], ""),
    ("zog", "Zog", "Pet Shop",
     ["Pet items and boosts. Everything except the pet."], ""),
    ("marco", "Marco", "Flower House",
     ["Ranked players get the Canvas Room. Everyone else gets the doorstep.",
      "Nice of you to knock, though."], ""),
    ("bartender", "Bartender", "Tavern",
     ["Brews, and the good sort.",
      "Kill ten zombies out past the graveyard and I'll pour you one."],
     "Time To Strike"),
    ("maddox", "Maddox the Slayer", "Tavern",
     ["Revenants, Tarantulas, Svens. Pay up front and I'll point you at one.",
      "The ones who don't pay up front don't come back."], ""),
    ("taylor", "Taylor", "Fashion Shop",
     ["The Fashion Shop. Some of it even has stats."], ""),
    ("seymour", "Seymour", "Fashion Shop",
     ["Tuxedos. Cheap, Fancy and Elegant.",
      "They fix your health and double your damage. Bold choice."], ""),
    ("scoop", "Scoop", "Mountain",
     ["Snow Shovel. You'll want one before you go north."], ""),
    ("curator", "Curator", "Museum",
     ["Put a thing in the Museum and it's out of your hands forever.",
      "That's rather the point."], ""),
    ("goldsworth", "Madame Eleanor Q. Goldsworth III", "Museum",
     ["I appraise. I do not flatter.",
      "Show me the collection and I'll tell you what it's worth."], ""),
    ("lonely_philosopher", "Lonely Philosopher", "Ruins",
     ["A Travel Scroll to the Hub Castle. Nobody ever buys it.",
      "I don't blame them."], ""),

    # ------------------------------------------------------------- the barn
    ("farmer", "Farmer", "The Barn",
     ["Ten wheat. That's all I'm asking.",
      "Then come and find me at The Barn."], "First Harvest"),
    ("farmhand", "Farmhand", "The Barn",
     ["One of every crop — wheat, carrot, potato, melon, pumpkin.",
      "Do that and there's Enchanted Bread in it for you."],
     "Back at the Barnyard"),
    ("windmill_operator", "Windmill Operator", "The Barn",
     ["Sixty-four string and sixty-four cobblestone and the mill turns again.",
      "After that I'll buy crops same as anyone."], ""),
    ("arthur", "Arthur", "The Barn",
     ["Compactors. Put one in a Minion and it stops filling up with rubbish.",
      "That Wheat Minion over there is mine."], ""),

    # -------------------------------------------------------- mushroom desert
    ("beth", "Beth", "Mushroom Desert",
     ["Jake's out past the dunes with all those axes.",
      "Past The Barn there's nothing but sand. Go and see."],
     "Intermediate Farmer"),
    ("mason", "Mason", "Mushroom Desert",
     ["The Treasure Hunter'll take your coins and give you a riddle.",
      "Sometimes there's treasure at the end of it."], ""),
    ("friendly_hiker", "Friendly Hiker", "Mushroom Desert",
     ["My brother's up the gorge and he's starving.",
      "Feed him before he gives up and wanders off."], ""),
    ("hungry_hiker", "Hungry Hiker", "Mushroom Gorge",
     ["Food. Any food. I'm not fussy.",
      "Leave me two days and I won't be here."], ""),
    ("treasure_hunter", "Treasure Hunter", "Treasure Hunter Camp",
     ["A hundred coins buys a vague clue. Fifty thousand buys a good one."], ""),
    ("shepherd", "Shepherd", "Shepherd's Keep",
     ["Shear every sheep in the Keep and come back to me.",
      "Four Pelts for your trouble."], ""),
    ("jake", "Jake", "Jake's House",
     ["Bring the animal to my house and I'll sell you its axe.",
      "A thousand coins each, and it doubles what that animal drops."], ""),
    ("hunter_ava", "Hunter Ava", "Mushroom Desert",
     ["There's an Elusive Animal out there. Trevor's the one to ask."], ""),
    ("tammy", "Tammy", "Trapper's Den",
     ["I keep the book on what can be hunted and where."], ""),
    ("tony", "Tony", "Trapper's Den",
     ["Tier twelve Farming Minions. The last ones you'll ever buy."], ""),
    ("trevor", "Trevor", "Trapper's Den",
     ["I'll name an animal, you kill it, I pay in Pelts.",
      "Simple arrangement."], ""),
    ("farmer_jon", "Farmer Jon", "Mushroom Desert",
     ["There was a sugar cane contest once. I still think about it."], ""),

    # ---------------------------------------------------------- the gold mine
    ("gold_forger", "Gold Forger", "Gold Mine",
     ["Gold items, and a Fancy Sword if you fancy one."], ""),
    ("iron_forger", "Iron Forger", "Gold Mine",
     ["Iron gear and chainmail armour. Nothing clever."], ""),
    ("rusty", "Rusty", "Gold Mine",
     ["Lost a quest item? I keep the ones that come back.",
      "Soulbound things always find their way to me."], ""),
    ("lazy_miner", "Lazy Miner", "Gold Mine",
     ["I've lost my pickaxe somewhere down there.",
      "Fetch it and it's yours. Smelting Touch on it and all."], "Lost and Found"),

    # -------------------------------------------------------- the deep caverns
    ("walter", "Walter", "Deep Caverns",
     ["Superboom TNT. Takes a wall down and doesn't argue."], ""),
    ("lapis_miner", "Lapis Miner", "Deep Caverns",
     ["A Lapis Pickaxe. Bring me one and I'll give you a Compactor."],
     "Helpful Miner"),
    ("redstone_miner", "Redstone Miner", "Deep Caverns",
     ["Redstone. All of it. Every piece you can carry.",
      "Four Accessory Bag slots for the lot."], ""),
    ("rhys", "Rhys", "Deep Caverns",
     ["Dwarves. Under the mountain. Mining XII and they'll let you in.",
      "The Dwarven Mines make this place look like a sandpit."],
     "There are Dwarves?"),
    ("lift_operator", "Lift Operator", "Gunpowder Mines",
     ["The lift goes down. Lapis Quarry, Pigmen's Den, Slimehill and worse.",
      "Mining V before I'll take you anywhere."], "Going Deeper"),

    # ------------------------------------------------------- the dwarven mines
    ("rhys_dwarven", "Rhys (Dwarven)", "Dwarven Village",
     ["Made it, then. I'll show you round.",
      "Mithril's everywhere. Titanium isn't."], ""),
    ("bulvar", "Bulvar", "Dwarven Village",
     ["Tier twelve Mining Minions. Straight to the top."], ""),
    ("bubu", "Bubu", "Dwarven Village",
     ["Pickaxes and Biofuel. One's no use without the other."], ""),
    ("blacksmith_dwarven", "Blacksmith (Dwarven)", "Dwarven Village",
     ["Reforges, dwarven style. Same anvil, better stones."], ""),
    ("old_man_garry", "Old Man Garry", "Dwarven Village",
     ["There's always an event on. Mithril Powder, Goblin Raids, the lot.",
      "Ask me which one and I'll tell you."], ""),
    ("banker_broadjaw", "Banker Broadjaw", "Dwarven Village",
     ["Same bank, deeper hole.",
      "Your coins are as safe down here as they are up there."], ""),
    ("bednom", "Bednom", "Dwarven Village",
     ["I had a dream about the mountain. It wasn't a good one."], ""),
    ("tarwen", "Tarwen", "Dwarven Tavern", ["*burp* Tankard?"], ""),
    ("hornum", "Hornum", "Dwarven Tavern", ["*burp* Another."], ""),
    ("gimley", "Gimley", "Dwarven Tavern", ["*burp* You'll want one of these."], ""),
    ("sargwyn", "Sargwyn", "Dwarven Tavern", ["*burp* Sit down, then."], ""),
    ("king_brammor", "King Brammor", "Royal Palace",
     ["A Commission. Do it and the Dwarves will remember you."], ""),
    ("king_emkam", "King Emkam", "Royal Palace",
     ["Commissions. One at a time, mind."], ""),
    ("king_redros", "King Redros", "Royal Palace",
     ["The mountain gives to those who work it."], ""),
    ("king_erren", "King Erren", "Royal Palace",
     ["Another Commission, if you've the back for it."], ""),
    ("king_thormyr", "King Thormyr", "Royal Palace",
     ["Mithril doesn't mine itself."], ""),
    ("king_emmor", "King Emmor", "Royal Palace",
     ["Work first. Titles after."], ""),
    ("king_grandan", "King Grandan", "Royal Palace",
     ["Seven kings and one mountain. It works better than you'd think."], ""),
    ("tornora", "Tornora", "Royal Palace",
     ["Seven of them. Seven! And they all think they're in charge."], ""),
    ("queen_mismyla", "Queen Mismyla", "Royal Palace",
     ["Kings come and go. The mountain stays."], ""),
    ("royal_resident", "Royal Resident", "Barracks of Heroes",
     ["You look like someone who deserves cake.",
      "Take it. Don't ask what's in it."], ""),
    ("royal_guard", "Royal Guard", "Royal Palace",
     ["Move along."], ""),
    ("castle_guard", "Castle Guard", "Royal Palace",
     ["Nothing to see."], ""),
    ("fetchur", "Fetchur", "Dwarven Mines",
     ["I want twenty of something and I'll tell you what tomorrow.",
      "Bring it and there's a reward in it."], ""),
    ("gwendolyn", "Gwendolyn", "Dwarven Mines",
     ["Ten thousand coins and the Crystal Hollows are yours.",
      "What happens in there is your business."], ""),
    ("geo", "Geo", "Dwarven Mines",
     ["Gemstones. Twelve kinds, five grades each.",
      "Rough, Flawed, Fine, Flawless, Perfect. In that order."], ""),
    ("lumina", "Lumina", "Dwarven Mines",
     ["Torches, lanterns, and the InfiniTorch that never runs out."], ""),
    ("fragilis", "Fragilis", "Dwarven Mines",
     ["Every ore block down here, and what it's worth breaking.",
      "Hard Stone isn't worth breaking. Now you know."], ""),
    ("station_master", "Station Master", "Dwarven Mines",
     ["Rails run everywhere. Tell me where and I'll send you."], ""),
    ("ticket_master", "Ticket Master", "Dwarven Mines",
     ["Ticket first. Then the ride."], ""),
    ("dirt_guy", "Dirt Guy", "Dwarven Mines",
     ["Give me the InfiniDirt Wand and I'll give you something Precious."], ""),
    ("dalbrek", "Dalbrek", "Dwarven Mines",
     ["The Cult of the Fallen Star. They meet where the sky drops things."], ""),
    ("puzzler", "Puzzler", "Dwarven Mines",
     ["A puzzle a day, and Mithril Powder for solving it."], ""),
    ("tal_ker", "Tal Ker", "Dwarven Mines",
     ["Hm."], ""),
    ("resident_snooty", "Royal Resident (Snooty)", "Royal Palace",
     ["I don't talk to peasants."], ""),
    ("resident_neighbor", "Royal Resident (Neighbour)", "Royal Palace",
     ["My neighbour. Where do I start."], ""),
    ("bylma", "Bylma", "Dwarven Mines",
     ["That bridge by the Great Ice Wall. Somebody should look at it."], ""),
    ("emissary_carlton", "Emissary Carlton", "Dwarven Mines",
     ["A Commission from the Kings. Take it or don't."], ""),
    ("emissary_ceanna", "Emissary Ceanna", "Dwarven Mines",
     ["Commissions. Always more Commissions."], ""),
    ("emissary_wilson", "Emissary Wilson", "Dwarven Mines",
     ["Work for the Kings, get paid by the Kings."], ""),
    ("emissary_lilith", "Emissary Lilith", "Dwarven Mines",
     ["I hand out Commissions. That's the whole job."], ""),
    ("emissary_fraiser", "Emissary Fraiser", "Dwarven Mines",
     ["Another Commission for you."], ""),
    ("emissary_eliza", "Emissary Eliza", "Dwarven Mines",
     ["Commission's ready when you are."], ""),
    ("emissary_braum", "Emissary Braum", "Dwarven Mines",
     ["Take the Commission. The Powder's worth it."], ""),
    ("malmar", "Malmar", "Dwarven Mines",
     ["Mining Pumpkin. Wear it. Don't ask."], ""),
    ("silnar", "Silnar", "Cliffside Veins",
     ["Wearing a Fallen Star Helmet? Then this Lozenge is yours."], ""),
    ("forger", "Forger", "The Forge",
     ["The Forge takes time and gives back better.",
      "Leave it in and come back later."], ""),
    ("fred", "Fred", "The Forge",
     ["Sixty-four Foul Flesh and I'll give you my Abiphone number.",
      "It's a fair trade. Sort of."], ""),
    ("jotraeline", "Jotraeline Greatforge", "The Forge",
     ["Drills. I open the anvil, you do the upgrading."], ""),
    ("dulin", "Dulin", "Dwarven Base Camp",
     ["Base Camp's this way. Glacite Tunnels are colder still."], ""),
    ("cold_enjoyer", "Cold Enjoyer", "Dwarven Base Camp",
     ["Cold builds up and Cold Resistance holds it off.",
      "Let it build up too far and you'll find out why it matters."], ""),
    ("sorhen", "Sor'Hen", "Dwarven Base Camp",
     ["Suspicious Scrap. Don't ask what's suspicious about it."], ""),
    ("scardius", "Scout Scardius", "Glacite Tunnels",
     ["Things in the Mineshafts hit harder than they look.",
      "Bring a pickaxe you don't mind swinging at them."], ""),
    ("plinius", "Scout Plinius", "Glacite Tunnels",
     ["The Tunnels go on further than anyone's mapped."], ""),
    ("emissary_lissandra", "Emissary Lissandra", "Glacite Tunnels",
     ["Commissions, out here in the cold."], ""),
    ("dr_stone", "Dr. Stone", "Fossil Research Center",
     ["Fossils in, pet recipes out. The Forge does the rest."], ""),

    # ------------------------------------------------------ the crystal hollows
    ("king_yolkar", "King Yolkar", "Crystal Hollows",
     ["Three Goblin Eggs and you'll carry the King's Scent for twenty minutes.",
      "They'll leave you alone. Mostly."], ""),
    ("professor_robot", "Professor Robot", "Crystal Hollows",
     ["Automaton Parts. Bring them and the Sapphire Crystal is yours."], ""),
    ("kalhuiki_door_guardian", "Kalhuiki Door Guardian", "Jungle",
     ["No Jungle Key, no temple. Those are the rules."], ""),
    ("keeper_of_lapis", "Keeper of Lapis", "Jungle",
     ["Scavenged Lapis. Then we'll talk about the Jade Crystal."], ""),
    ("keeper_of_gold", "Keeper of Gold", "Jungle",
     ["Scavenged Gold. Bring it here."], ""),
    ("keeper_of_diamond", "Keeper of Diamond", "Jungle",
     ["Scavenged Diamond. Nothing else will do."], ""),
    ("keeper_of_emerald", "Keeper of Emerald", "Jungle",
     ["Scavenged Emerald, and the Jade Crystal opens."], ""),
    ("sludge", "Sludge", "Crystal Hollows",
     ["Free me and there's a chest in it for you.",
      "I'd shake on it but, well."], ""),
    ("xalx", "Xalx", "Crystal Hollows",
     ["Mysterious Meat. It is meat. That much I'll swear to."], ""),
    ("three_bears", "The Three Bears", "Crystal Hollows",
     ["Sit down. This won't take long.",
      "...and then we were gone."], ""),
    ("odawa", "Odawa", "Jungle Village",
     ["Masks, amulets, spears and Jungle Keys.",
      "The Jungle Pickaxe is the one you want."], ""),
    ("geonathan", "Geonathan Greatforge", "Crystal Nucleus",
     ["Drill mechanic. Same anvil as my sister, better view."], ""),
    ("emissary_sisko", "Emissary Sisko", "Crystal Nucleus",
     ["Commissions, right in the middle of it all."], ""),
    ("gemma", "Gemma", "Crystal Nucleus",
     ["Diamond Essence. Spend it here."], ""),
    ("chunk", "Chunk", "Precursor Remnants",
     ["Superboom TNT. You'll need more than you think."], ""),

    # ---------------------------------------------------------- spider's den
    ("haymitch", "Haymitch", "Spider's Den",
     ["Up the nest it gets worse. That's the whole geography of the place."], ""),
    ("rick", "Rick", "Spider's Den",
     ["Two iron ingots and the Promising Shovel is yours.",
      "Flint Bros, we're called. Don't ask."], "The Flint Bros"),
    ("grandma_wolf", "Grandma Wolf", "Spider's Den",
     ["The Grandma Wolf pet. I give them out and I upgrade them.",
      "Mind your manners and it'll like you."], ""),
    ("shaggy", "Shaggy", "Spider's Den",
     ["Arachne. She's down there and she's waiting.",
      "Find the Relics first if you've any sense."], ""),
    ("bramass", "Bramass Beastslayer", "Spider's Den",
     ["The Bestiary counts everything you've killed.",
      "Kill enough of one thing and it pays you for it."], ""),
    ("archaeologist", "Archaeologist", "Spider's Den",
     ["Relics. Scattered, buried, and worth finding."], ""),
    ("spider_tamer", "Spider Tamer", "Arachne's Sanctuary",
     ["Arachne again. And the Spider Essence Shop, while you're here."], ""),

    # --------------------------------------------------------- the crimson isle
    ("elle", "Elle of the Nether", "Crimson Isle",
     ["The Magma Cube Boss comes round on a timer. Everyone fights it at once.",
      "Bring nether wart and a blaze rod before you even think about it."],
     "Warrior's Quest"),

    # ---------------------------------------------------------------- the park
    ("charlie", "Charlie", "The Park",
     ["Sixty-four Birch Wood and there's a hundred coins in it.",
      "After that, Dark Oak, and I'll find you some Small Storage."],
     "Into the Woods"),
    ("vanessa", "Vanessa", "The Park",
     ["Five thousand coins buys you a minute of rain.",
      "You'd be surprised how often that's worth it."], ""),
    ("gustave", "Gustave", "Spruce Woods",
     ["The Woods Race. Beat the clock and the prizes get better."],
     "Woods Racing"),
    ("melancholic_viking", "Melancholic Viking", "Viking Longhouse",
     ["Not until the ritual's done. I don't make the rules.",
      "After that — Viking's Tear, Raider Axe, and a scroll to the Jungle."], ""),
    ("ryan", "Ryan", "Dark Thicket",
     ["The Trial of Fire. Waves of them, one after another.",
      "Campfire Initiate Badge to start. It gets better as you do."],
     "Trial of Fire"),
    ("melody", "Melody", "Savanna Woodland",
     ["Play my songs on the Harp and I'll give you Intelligence for it.",
      "And a lock of my hair, if you finish them all."], "Melody"),
    ("master_tactician_funk", "Master Tactician Funk", "Savanna Woodland",
     ["Wood Singularity and the Tactician's Sword.",
      "Neither is cheap and both are worth it."], ""),
    ("juliette", "Juliette", "Jungle Island",
     ["Romero won't speak to me and I won't speak first.",
      "You could carry a message. If you wanted."], "Romero and Juliette"),
    ("romero", "Romero", "Jungle Island",
     ["Juliette knows what she did.",
      "...she said what, exactly? Bring me something and I'll think about it."], ""),
    ("old_shaman_nyko", "Old Shaman Nyko", "Howling Cave",
     ["True Essence, and the book that goes with it.",
      "True Defence stops what ordinary Defence doesn't."], ""),

    # ------------------------------------------------------------------ the end
    ("pearl_dealer", "Pearl Dealer", "The End",
     ["Stonk, Dragon Hunter books, Ender Slayer books. End things.",
      "The Dragon's Nest is through there. Combat XII."],
     "Beginning of The End"),
    ("gregory", "Gregory", "Dragon's Nest",
     ["Decent Bow. Flint Arrows. Only while the Dragon's up."], ""),
    ("guber", "Guber", "The End",
     ["The End Race. Nobody finishes it first time.",
      "Nobody finishes it second time either."], "The End Race"),
    ("lone_adventurer", "Lone Adventurer", "The End",
     ["First time here? Stay off the Zealots until you can take one.",
      "Everything on this island can kill you and most of it will."], ""),
    ("tyzzo", "Tyzzo", "Dragon's Nest",
     ["Dragon Essence, and the Draconic Altar if you've eight Summoning Eyes."], ""),

    # -------------------------------------------------------------- the dungeons
    ("malik", "Malik", "Dungeon Hub",
     ["Reforge stones, upgrades, salvage, and the Essence Shop.",
      "Everything you drag out of the Catacombs goes through me."], ""),
    ("mort", "Mort", "Dungeon Hub",
     ["I open the gate. Bring a party or bring regret."], ""),
    ("ophelia", "Ophelia", "Dungeon Hub",
     ["Dungeon gear. The good stuff and the stuff that keeps you alive."], ""),
    ("dungeon_hub_selector", "Dungeon Hub Selector", "Dungeon Hub",
     ["Another lobby, if this one's full."], ""),
    ("guildford", "Guildford", "Dungeon Hub",
     ["Races. Around the Hub, against the clock."], ""),
    ("tomioka", "Tomioka", "The Catacombs",
     ["Enchanted books, down here where you need them."], ""),
    ("duncan", "Duncan", "The Catacombs",
     ["Epic Farming Exp Boost. One and a half million coins.",
      "I don't negotiate."], ""),
    ("winona", "Winona", "The Catacombs",
     ["Revive Stones. A hundred thousand each and worth every coin."], ""),
    ("trinity", "Trinity", "The Catacombs",
     ["Potions. Drink them before the fight, not during."], ""),
    ("wizard_catacombs", "Wizard (Catacombs)", "The Catacombs",
     ["A Crystal Ball for a Blessing of Wisdom. Fair, I'd say."], ""),
    ("zodd", "Zodd", "The Catacombs",
     ["General's Medallion. A million coins. Take it or leave it."], ""),

    # ------------------------------------------------------------- winter island
    ("st_jerry", "St. Jerry", "Jerry's Workshop",
     ["Twenty White Gifts scattered over the island.",
      "Find them all and there's a Green one waiting."], ""),
    ("sherry", "Sherry", "Jerry's Workshop",
     ["Winter things. Only here, only now."], ""),
    ("gulliver", "Gulliver", "Jerry's Workshop",
     ["The Chicken Race. It is exactly what it sounds like."], ""),
    ("frosty", "Frosty", "Jerry's Workshop",
     ["Frosty the Snow Cannon. I'll refill it and the Blaster too."], ""),
    ("gary", "Gary", "Jerry's Workshop",
     ["Refills here. And if it's down to one gift pile, I'll fight beside you."], ""),
    ("terry", "Terry", "Jerry's Workshop",
     ["Salty and Treacherous. Fishing rods only."], ""),
    ("banker_barry", "Banker Barry", "Jerry's Workshop",
     ["Same bank, colder hands."], ""),

    # --------------------------------------------------------------- the rift
    ("alatar", "Alatar", "Rift — Wizard Tower",
     ["Time runs differently here. You'll feel it before you understand it."], ""),
    ("wizard_but_weird", "Wizard But Weird", "Rift",
     ["This is the Rift. It is not where you were.",
      "Do something for me and I'll give you the Guide."], ""),
    ("wizardman", "Wizardman", "Rift — Wizard Tower",
     ["I am saving the multiverse. You're welcome."], ""),
    ("elise_rift", "Elise", "Rift",
     ["The Gallery, and the Necklace that goes with it."], ""),
    ("enigma", "Enigma", "Enigma's Crib",
     ["Enigma Souls. Hidden, all of them, and none of them by accident.",
      "Find enough and the Cloak is yours."], ""),
    ("motes_grubber", "Motes Grubber", "Rift",
     ["Feed me Rift items. I'll pay in Motes."], ""),
    ("argofay_bughunter", "Argofay Bughunter", "Wyld Woods",
     ["Silkwire Stick. Safety Belt. Do the job and they're yours."], ""),
    ("argofay_bugshopper", "Argofay Bugshopper", "Wyld Woods",
     ["Larva Hook, Odonata Bottle, and a surgery kit you hope not to need."], ""),
    ("argofay_serialbather", "Argofay Serialbather", "Wyld Woods",
     ["Stability Elixir. Steadies the ground under you."], ""),
    ("argofay_sonfather", "Argofay Sonfather", "Wyld Woods",
     ["An Argofay begins, an Argofay continues, an Argofay concludes."], ""),
    ("argofay_threebrother", "Argofay Threebrother", "Wyld Woods",
     ["Wyld Sword. Three of us sell it. Don't ask why."], ""),
    ("argofay_trafficker", "Argofay Trafficker", "Wyld Woods",
     ["Wyld armour, one piece per trafficker. We're spread out on purpose."], ""),
    ("argofay_trailblazer", "Argofay Trailblazer", "Wyld Woods",
     ["Why don't bees ever get lost? ...never mind."], ""),
    ("argofay_treemerger", "Argofay Treemerger", "Wyld Woods",
     ["Am I the tree, or is the tree me? I've had a long day."], ""),
    ("argofay_tencounter", "Argofay Tencounter", "Wyld Woods",
     ["One. Two. Three. Four. Five. Six. Seven. Eight. Nine. Ten."], ""),
    ("hound", "Hound", "Wyld Woods",
     ["Get the Wyld Armor. All of it. Then come back."], ""),
    ("inverted_sirius", "Inverted Sirius", "Wyld Woods",
     ["Some things carry back out of the Rift. Most don't.",
      "Take the Doubloon of the Family."], ""),
    ("jacquelle", "Sad Jacquelle", "Wyld Woods",
     ["Montezuma. That's all I'll say about it."], ""),
    ("kiermet", "Kiermet", "Wyld Woods",
     ["There's a Soul near here. Ribbit knows more."], ""),
    ("ribbit", "Ribbit", "Wyld Woods", ["Ribbit."], ""),
    ("tel_kar", "Tel Kar", "Wyld Woods",
     ["The Rift is what's left when time stops paying attention.",
      "Here. A Soul, for listening."], ""),
    ("alabaster", "Alabaster", "Shifted Tavern",
     ["Dackinoru. Go and ask him."], ""),
    ("arora", "Arora", "Shifted Tavern", ["Don't mind us. Carry on."], ""),
    ("ashera", "Ashera", "Shifted Tavern", ["Garlacius is who you want."], ""),
    ("chester", "Chester", "Shifted Tavern", ["Lazarus. Next one along."], ""),
    ("dackinoru", "Dackinoru", "Shifted Tavern", ["Chester. Ask Chester."], ""),
    ("fafnir", "Fafnir", "Shifted Tavern",
     ["Argofay Serialbather. Out in the Woods."], ""),
    ("garlacius", "Garlacius", "Shifted Tavern", ["Fafnir's your next stop."], ""),
    ("lazarus", "Lazarus", "Shifted Tavern", ["Vreike. Keep going."], ""),
    ("seskel", "Seskel", "Shifted Tavern", ["We're all in on it, you know."], ""),
    ("shifted", "Shifted", "Shifted Tavern",
     ["Start with Alabaster. It's a long chain and it's the point."], ""),
    ("tybalt", "Tybalt", "Shifted Tavern", ["Another round, is it."], ""),
    ("vreike", "Vreike", "Shifted Tavern", ["Ashera. Then you're nearly done."], ""),
    ("porhtal", "Porhtal", "Broken Cage",
     ["The Rift Eyes. They see what you can't."], ""),
    ("unbound_explorer", "Unbound Explorer", "Otherside",
     ["Wyld Woods, if you want. Say the word."], ""),
    ("dr_edwin", "Dr. Edwin", "Black Lagoon",
     ["The Leeches Lair. Down there. Try not to be down there long."], ""),
    ("dr_phear", "Dr. Phear", "Leeches Lair",
     ["Want out? Of course you want out."], ""),
    ("mushroom_guy", "Mushroom Guy", "Black Lagoon",
     ["Mushrooms here work differently. Everything here works differently."], ""),
    ("kay", "Kay", "Lagoon Hut",
     ["A paper for Dr. Edwin. And I'll take Lil' Pads for Motes."], ""),
    ("reed", "Reed", "Lagoon Hut", ["Rift Boat. You'll want one."], ""),
    ("roy", "Roy", "Lagoon Hut", ["An Enigma Soul. Going cheap. Relatively."], ""),
    ("alchemist_west", "Alchemist (West Village)", "Rift — West Village",
     ["Anti-Morph Potion. Seraphine needs it more than you do."], ""),
    ("chef", "Chef", "Rift — West Village",
     ["Beat my challenge and there's a Soul in it."], ""),
    ("cosmo", "Cosmo", "Rift — West Village",
     ["Dolphin Trainer's through here. There's a Soul at the far end."], ""),
    ("finplex", "Finplex", "Rift — West Village",
     ["Zoop the Fish. Yes, that's its name."], ""),
    ("grandma", "Grandma", "Rift — West Village",
     ["Booster Cookies were cheaper in my day. They always were."], ""),
    ("gunther", "Gunther", "Rift — West Village",
     ["The Rift Race. Dark Pebble and a Gunthesizer Lichen at the end."], ""),
    ("joey_mcpizza", "Joey McPizza", "Rift — West Village",
     ["Challenge's simple. Doing it isn't. Soul at the end."], ""),
    ("plumber_joe_rift", "Plumber Joe (Rift)", "Rift — West Village",
     ["Plumber's Bucket. Different Rift, same job."], ""),
    ("skylark", "Skylark", "Rift — West Village",
     ["Yoshua reckons we're in a game.",
      "I've stopped arguing."], ""),
    ("sorcerer_okron", "Sorcerer Okron", "Rift — West Village",
     ["Defend the house and the Warding Trinket is yours."], ""),
    ("unhinged_kloon", "Unhinged Kloon", "Rift",
     ["A puzzle. Solve it and take the Defective Monitor."], ""),
    ("yoshua", "Yoshua", "Rift — West Village",
     ["We're in a game, Skylark. I can feel it."], ""),
    ("dr_emmett", "Dr. Emmett", "Mirrorverse",
     ["The Mirrorverse. Everything's the same and nothing is."], ""),
    ("disinfestor", "Disinfestor", "Infested House",
     ["...it's in the walls."], ""),
    ("kat_rift", "Kat (Rift)", "Infested House",
     ["Clear the house out. Vermin Belt, a Ferret, and a Soul for the key."], ""),
    ("shania", "Shania", "Dreadfarm",
     ["The Wand of Farming. Point it at the crops and let it work.",
      "Proto-Chicken's for sale too."], ""),
    ("sick_farmer", "Sick Farmer", "Dreadfarm", ["*cough*"], ""),
    ("cowboy_nick", "Cowboy Nick", "Rift — Village Plaza",
     ["Horsezooka. It fires a horse. That is the entire item."], ""),
    ("cryptosis", "Cryptosis", "Rift — Village Plaza",
     ["An Enigma Soul, if the price suits you."], ""),
    ("marcia", "Marcia", "Rift — Village Plaza",
     ["Detective Amog's asking questions. I've answered mine."], ""),
    ("roger", "Roger", "Rift — Village Plaza",
     ["Travel Scroll to the Wizard Tower. Saves the walk."], ""),
    ("detransfigured_seraphine", "Detransfigured Seraphine", "Barry Center",
     ["Look at my face. Look at it.",
      "Get me the Anti-Morph Potion and I'll sell you the old one."], ""),
    ("creed", "Creed", "Barry Center", ["Barry has a plan. Barry always has a plan."], ""),
    ("dust", "Dust", "Barry Center", ["Filing. Endless filing."], ""),
    ("frankie", "Frankie", "Barry Center", ["You're not on the list."], ""),
    ("harriette", "Harriette", "Barry Center", ["Barry Center. How may I redirect you."], ""),
    ("soma", "Soma", "Barry Center",
     ["Solve this and they'll move me to HQ. Please solve this."], ""),
    ("stain", "Stain", "Barry Center", ["Don't touch anything."], ""),
    ("violetta", "Violetta", "Barry Center",
     ["Another maths puzzle. Get it right and I'm promoted."], ""),
    ("barry", "Barry", "Barry HQ",
     ["Scorpius took the coins. Every last one of them.",
      "I'll turn this world upside down before I'm finished."], ""),
    ("joliet", "Joliet", "Rift — Taylor's", ["Mm."], ""),
    ("seymour_rift", "Seymour (Rift)", "Rift — Taylor's",
     ["Exceedingly Comfy Sneakers. The name is the review."], ""),
    ("taylor_rift", "Taylor (Rift)", "Rift — Taylor's", ["Browse. Don't dawdle."], ""),
    ("ramero", "Ramero", "Murder House", ["...you shouldn't be in here."], ""),
    ("detective_amog", "Detective Amog", "Rift",
     ["A murder, backwards. Work out who didn't do it.",
      "Ring of Broken Love when you're done."], ""),
    ("jerry_rift", "Jerry (Rift)", "Rift — 'Your' Island",
     ["I am the bedrock of the Universe.",
      "No, really."], ""),
    ("lonely_avaeikx", "Lonely Ävaeìkx", "Lonely Terrace",
     ["...",
      "(sit near them for three minutes, but not with them)"], ""),
    ("damia", "Damia (Rift)", "Barrier Street", ["Street's closed. Ask Barry."], ""),
    ("blacksmith_dejavu", "Blacksmith (Déjà Vu Alley)", "Déjà Vu Alley",
     ["Haven't we done this already?"], ""),
    ("rock", "Rock", "Living Stillness", ["..."], ""),
    ("master_tactician_fink", "Master Tactician Fink", "Rift — Colosseum",
     ["Tactician's Murder Weapon. For the detective, presumably."], ""),
    ("mole", "Mole", "Rift — Colosseum",
     ["Full Circle. Do it and there's a Soul waiting."], ""),
    ("deer", "Deer", "Photon Pathway",
     ["Rift Boat to Stillgore Château. Hop on."], ""),
    ("phaser", "Phaser", "Photon Pathway",
     ["Can't do the parkour? I'll skip you past it. For a price."], ""),
    ("maddox_rift", "Maddox the Slayer (Rift)", "Stillgore Château",
     ["Vampires. Different slayer, same arrangement."], ""),
    ("fairylosopher", "Fairylosopher", "Fairylosopher Tower",
     ["A Soul, and a lecture you didn't ask for."], ""),
    ("tia", "Tia the Fairy", "Wilderness",
     ["Fairy Souls. Two hundred and forty of them, hidden everywhere.",
      "Bring them to me and I'll make you permanently better."], ""),
    ("lucius", "Lucius", "Wilderness",
     ["The Shady Ring, and upgrades for it. Don't ask where I got them."], ""),
    ("shifty", "Shifty", "Wilderness",
     ["Brews. Cheap ones. Nobody's watching."], ""),
    ("sirius", "Sirius", "Wilderness",
     ["Dark Auction. Midnight, every third day.",
      "Come early. It fills up."], ""),
    ("wizard", "Wizard", "Wizard Tower",
     ["My Portal goes places. That's all a portal has to do."], ""),
    ("barry_wizard", "Barry (Wizard Tower)", "Wizard Tower",
     ["City Projects. I organised them. Scorpius took the coins.",
      "One day I'll turn this world upside down."], ""),
    ("elise", "Elise", "Wizard Tower",
     ["New necklace. Do you like it? Be honest."], ""),
    ("nicole", "Nicole", "Wizard Tower",
     ["Books, mostly. And a coffee, if you're offering."], ""),
    ("pat", "Pat", "Graveyard",
     ["Gravel and flint. Somebody has to sell it."], ""),
    ("lumber_jack", "Lumber Jack", "Forest",
     ["Chop enough logs and there's a Sweet Axe in it for you."], "Timber!"),
    ("fisherman", "Fisherman", "Fisherman's Hut",
     ["Sit still. Watch the float. That's fishing.",
      "Five clay and I'll hand you a Prismarine Rod."], "Fishing Tutorial"),
]
